### ISSUE TITLE
All posts with @here/@everyone are ignored

### ISSUE THREAD

**Issue by tadeokondrak** [tadeokondrak/AvoidBot#1]

**Comment by seraku24** [comment]
What was the original intent for those checks in the code?  I just persisted them (albeit with a singular regex).

**Comment by tadeokondrak** [comment]
Merging the refactored code undid this fix, to fix: add a function which strips @here and @everyone.

**Comment by seraku24** [comment]
Ah.  I get it.  We don't want the bot using those mention types just because a user did, but we still want to respond to those posts.

**Comment by tadeokondrak** [comment]
Also, they both contain e, so they shouldn't respond to the post of there's no e in the rest of the post.

**Comment by tadeokondrak** [comment]
It should also strip other mentions too, so it doesn't ping people a second time.

**Comment by seraku24** [comment]
Should be fixed by #3.
