### ISSUE TITLE
ᗴ is allowed

### ISSUE THREAD

**Issue by DerfJagged** [tadeokondrak/AvoidBot#11]

**Comment by seraku24** [comment]
I was just filing an issue on this, but you beat me to it.

Also part of Canadian Aboriginal syllabics: ᗴ ᣯ ᣰ ᘿ ᙓ ᙦ ᗕ ᗛ

**Comment by DerfJagged** [comment]
More glyphs as said in chat: http://www.tamasoft.co.jp/en/general-info/unicode.html

**Comment by seraku24** [comment]
Yes.  We could do a preemptive pass over the entire Unicode set for look-alikes, but it might also just work to wait until examples show up.
