### ISSUE TITLE
Superfluous punctuation in replies.

### ISSUE THREAD

**Issue by seraku24** [tadeokondrak/AvoidBot#4]
![image](https://cloud.githubusercontent.com/assets/20533271/22996429/9a0ef494-f383-11e6-8327-54ea5a7030d1.png)

The logic for stripping out links and mentions may leave behind associated punctuation.

**Comment by tadeokondrak** [comment]
Fixed in c647707087bc685bbde69fb5a9c22ad04785dc59.
