### ISSUE TITLE
AvoidBot not actually banning folks.

### ISSUE THREAD

**Issue by seraku24** [tadeokondrak/AvoidBot#7]
From @DerfJagged on Discord:
> Hey guys, I noticed that AvoidBot on reddit isn't actually handing out bans, it just says it does. See the latest banned guy on the subreddit, I banned him myself but AvoidBot had left him a comment saying he was banned when he really wasn't

**Comment by tadeokondrak** [comment]
This was fixed in 3b70df58805b53ca212a6cd49cc0ada1d6c0dff5.

**Comment by tadeokondrak** [comment]
Nope. Wasn't fixed.
